# Generated by Django 5.1 on 2024-09-06 17:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption1', models.CharField(max_length=300, verbose_name='Caption 1')),
                ('copyright', models.CharField(max_length=300, verbose_name='Copyright')),
            ],
            options={
                'verbose_name': 'Footer caption',
                'verbose_name_plural': 'Footer caption',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('link', models.CharField(max_length=200, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='only_medias/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4', 'avi', 'mov', 'mp3', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv', 'zip', 'rar', 'pdf', 'ogg'])], verbose_name='File')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('gif', 'Gif'), ('other', 'Other')], max_length=10, verbose_name='File Type')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Media',
            },
        ),
        migrations.CreateModel(
            name='BottomMainPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=300, verbose_name='Caption')),
                ('back_image_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_image_1', to='common.media', verbose_name='Back image 1')),
                ('back_image_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='back_image_2', to='common.media', verbose_name='Back image 2')),
                ('header_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_image', to='common.media', verbose_name='Header image')),
            ],
            options={
                'verbose_name': 'Bottom part',
                'verbose_name_plural': 'Bottom part',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200, verbose_name='Link')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_pic', to='common.media', verbose_name='Social media picture')),
            ],
            options={
                'verbose_name': 'Social media',
            },
        ),
    ]
