# Generated by Django 5.1 on 2024-09-06 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BottomMainPart',
        ),
    ]
