# Generated by Django 5.1 on 2024-09-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_bottommainpart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Links',
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
