# Generated by Django 5.1 on 2024-09-10 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_referencesinfooter'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottommainpart',
            name='category_picture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_image', to='common.media', verbose_name='Category image'),
            preserve_default=False,
        ),
    ]
