# Generated by Django 5.1 on 2024-09-06 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=120, verbose_name='Headline')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ContactsAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=120, verbose_name='Emote')),
                ('headline', models.CharField(max_length=120, verbose_name='Headline')),
                ('link', models.CharField(max_length=120, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=120, verbose_name='Headline')),
                ('text', models.CharField(max_length=120, verbose_name='Text')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_us_image', to='common.media', verbose_name='About us image')),
            ],
            options={
                'verbose_name': 'About us',
                'verbose_name_plural': 'About us',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=300, verbose_name='Headline')),
                ('author', models.CharField(max_length=150, verbose_name='Headline')),
                ('interview_date', models.DateField(verbose_name='The date of interview')),
                ('text', models.TextField(verbose_name='Text')),
                ('audio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_article', to='common.media', verbose_name='Audio')),
                ('author_icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_icon', to='common.media', verbose_name="Author's icon")),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_article', to='common.media', verbose_name='Audio')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
