# Generated by Django 5.1 on 2024-09-06 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_article', to='common.media', verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='article',
            name='picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture_article', to='common.media', verbose_name='Image'),
        ),
    ]
