# Generated by Django 5.1 on 2024-09-10 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_level_category_lft_category_parent_and_more'),
        ('common', '0007_referencesinfooter'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='category_picture',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='category_image', to='common.media', verbose_name='Category image'),
            preserve_default=False,
        ),
    ]
